[tool.poetry]
name = "py-d2-additional-info"
version = "0.1.0"
description = ""
authors = ["Tian-que <1605206150@qq.com>"]

[tool.poetry.dependencies]
python = "^3.9"
bungieapi = {path = "../bungieapi"}
ujson = "^5.1.0"
aiofiles = "^0.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
