# This workflow runs when a PR is requested
name: Pull Request Flow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout D2AI
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Update pip
        run: python -m pip install --upgrade pip
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: '1.1.12'
      
      - name: Install Environment
        run: poetry install --no-dev

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Get D2 Manifest
        uses: nick-invision/retry@v2.0.0
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: poetry run python getManifest.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Generate new D2AI information
        run: poetry run python script.py
        env:
          LOG_LEVEL: "SUCCESS"

      - name: Check for new files
        id: data
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Commit other updated values
        if: steps.data.outputs.porcelain
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: other updates from manifest
          commit_user_name: D2 Manifest Bot
          commit_user_email: 1605206150tq@gmail.com
          commit_author: D2 Manifest Bot <1605206150tq@gmail.com>